### ISSUE TITLE
[DECX] Atomic level units

### ISSUE THREAD

**Issue by benjtinsley** [decx-press/decx-press#12]
## Description
Develop the foundational structure for **Atomic Units** in the  [Merkle DAG](https://whimsical.com/decx-press-merkle-dag-6FiFNjkeb3GnDY1wYm7nQX@2bsEvpTYSt1Hir1oiAYvzqqan74nt2xcnvf). An Atomic Unit represents a single UTF character that is hashed and stored. This feature will enable the storage of the smallest building blocks in the content hierarchy.
The implementation must ensure that:
1. Duplicate Atomic Units are not stored (deduplication).
2. Efficient lookup mechanisms are provided to check for existence ([Solidity mapping](https://www.geeksforgeeks.org/solidity-mappings/)).

### Storage
- [x] Each UTF character is hashed using a cryptographic hash function (e.g., [keccak256](https://ethereum.stackexchange.com/questions/11572/how-does-the-keccak256-hash-function-work)).
- [x] Atomic Units are stored in a mapping with their hash as the key.
- [x] Ensure that duplicate Atomic Units are not stored again.
### Lookup
- [x] Provide a method to query if an Atomic Unit exists by its hash
- [x] Provide a method to retrieve the original character from its hash
### Validation
- [x] Validate that only single UTF characters can be submitted as an Atomic Unit
- [x] Reject empty strings, invalid inputs, or strings longer than one character
### Gas Optimization
Ensure the implementation minimizes gas costs by:
- [x] Performing existence checks before storing
- [x] Hashing only if necessary, as hashing incurs cost
### Error Handling
- [x] Return meaningful errors for invalid inputs or duplicate Atomic Units

## Tasks
1. **Create Storage Structure**
Define a Solidity mapping for Atomic Unit storage, ie
```solidity
mapping(bytes32 => bool) public atomicHashes; // Tracks existence of hashes
mapping(string => bytes32) public atomicLookup; // Reverse lookup for original values
```
2. **Write a Function to Add Atomic Units**
General flow as:
- Accept a single UTF character as input.
- Hash the character.
- Check if the hash already exists in `atomicHashes`.
- If it does not exist:
   - Store the hash in `atomicHashes`.
   - Add a reverse mapping in `atomicLookup`.
3. **Write a Function to Check Existence**
Accept a hash as input and return whether the Atomic Unit exists.
4. **Write a Function to Retrieve an Atomic Unit**
Accept a hash as input and return the corresponding UTF character.
5. **Write Test Cases**
Validate the following:
- [x] Correct storage of unique UTF characters
- [x] Prevention of duplicate Atomic Unit storage.
- [x] Retrieval of Atomic Units by their hash.
- [x] Rejection of invalid inputs.

## Deliverables
1. Solidity code to handle Atomic Unit storage and lookup.
2. Unit tests with edge cases (e.g., duplicate characters, invalid inputs).

## Example Input and Expected Behavior
1. Input: `a`
- **Hash:** Compute `keccak256(abi.encodePacked("a"))`.
- **Storage:** Add to `atomicHashes` and `atomicLookup`.
2. Input: `a` again
- **Check:** `atomicHashes[hash] == true`.
- **Behavior:** Reject as a duplicate.
3. Query: `atomicHashes[hash]`
- **Result:**` true` if the Atomic Unit exists.
4. Query: `atomicLookup["a"]`
- **Result:** Returns the hash of "a".

## Definition of Done
- [ ] Code is deployed to the development environment.
- [x] All acceptance criteria are met.
- [x] Unit tests pass with 100% coverage for Atomic Unit logic.
- [ ] Code is reviewed and approved by at least two other team members.
