### ISSUE TITLE
[DECX] Composite level units

### ISSUE THREAD

**Issue by benjtinsley** [decx-press/decx-press#13]
## Description
Develop the structure and logic for **Composite Units** in the Merkle DAG. A Composite Unit represents a hash of two Atomic Units combined in sequential order. The implementation must:
1. Ensure that only exact pairs of Atomic Units are accepted as they appear in sequence (min 2, max 2).
2. Prevent duplicate Composite Units from being stored.
3. Enable efficient lookup to check if a Composite Unit already exists.

### Storage
- [x] Composite Units are formed by hashing two Atomic Unit hashes in sequential order. ie,
```solidity
compositeHash = keccak256(atomicHashA + atomicHashB)
```
- [x] Composite Units are stored in a mapping with their hash as the key.
- [x] Ensure that duplicate Composite Units are not stored again.
### Lookup
- [x] Provide a method to check if a Composite Unit exists by its hash.
### Validation
Validate that:
- [x] Both input Atomic Units exist in the `atomicHashes` mapping before forming a Composite Unit.
- [x] Inputs are exactly two Atomic Units.
- [x] Composite Units cannot be created from invalid or non-existent Atomic Units.
### Gas Optimization
Minimize gas costs by:
- [x] Checking for existence before storing
- [x] Hashing only if necessary.
### Error Handling:
- [x] Return meaningful errors for invalid inputs or duplicate Composite Units

## Tasks
1. **Create Storage Structure**
Define a Solidity mapping for Composite Unit storage. ie:
```solidity
mapping(bytes32 => bool) public compositeHashes; // Tracks existence of Composite Units
```
2. **Write a Function to Add Composite Units**
General flow as follows:
- Accept two Atomic Unit hashes as input.
- Validate that both hashes exist in `atomicHashes`.
- Compute the hash of the Composite Unit using the two Atomic Unit hashes, ie:
```solidity
bytes32 compositeHash = keccak256(abi.encodePacked(hashA, hashB));
```
- Check if the Composite Unit already exists in `compositeHashes`.
- If it does not exist, store it in the `compositeHashes` mapping.
3. **Write a Function to Check Existence**
Accept a Composite Unit hash as input and return whether it exists in `compositeHashes`.
4. **Write Test Cases**
Validate:
- [x] Correct storage of valid Composite Units.
- [x] Prevention of duplicate Composite Unit storage.
- [x] Rejection of invalid inputs (e.g., non-existent Atomic Units, more than two inputs).
- [x] Checking the existence of Composite Units.

## Deliverables
- [x] Solidity code to handle Composite Unit creation and deduplication.
- [x] Unit tests with edge cases (e.g., invalid inputs, duplicate pairs).

## Dependencies
- #12 

## Example Input and Expected Behavior
1. Input: `hashA`, `hashB`
- **Precondition:** `atomicHashes[hashA] == true` and `atomicHashes[hashB] == true`.
- **Composite Hash:** Compute `keccak256(abi.encodePacked(hashA, hashB))`.
- **Storage:** Add to `compositeHashes`.
3. Input:`hashA`, `hashB` again
- **Check:** `compositeHashes[compositeHash] == true`.
- **Behavior**: Reject as duplicate.
5. Query: `compositeHashes[compositeHash]`
- **Result:** `true` if the Composite Unit exists.
7. Invalid Input: `hashA` (exists), `hashC` (does not exist):
- **Behavior:** Reject with an error message, ie `"One or more Atomic Units do not exist"`.

## Definition of Done
- [ ] Code is deployed to the development environment.
- [ ] All acceptance criteria are met.
- [ ] Unit tests pass with 100% coverage for Composite Unit logic.
- [ ] Code is reviewed and approved by at least two other team members.
