### ISSUE TITLE
Blob level units

### ISSUE THREAD

**Issue by benjtinsley** [decx-press/decx-press#14]
## Description

Develop the structure and logic for **Blob Units** in the Merkle DAG. A Blob Unit represents a hash of exactly 3  Composite Units.

The implementation must:
1. [ ] Ensure that Blob Units are valid combinations based on these constraints.
2. [ ] Prevent duplicate Blob Units from being stored.
3. [ ] Enable efficient lookup to check if a Blob Unit already exists.

### Storage
Blob Units are formed by hashing the hashes of:
- Exactly 3 Composite Units.
- Blob Units are stored in a mapping with their hash as the key.
- Ensure that duplicate Blob Units are not stored again.
### Lookup
Provide a method to check if a Blob Unit exists by its hash.
### Validation
Validate that:
- Composite Units referenced in a Blob exist in the `compositeHashes` mapping.
- Input elements must be exactly 3 Composite Units.
### Gas Optimization
Minimize gas costs by:
- Checking for existence before storing.
- Hashing only if necessary.
### Error Handling
Return meaningful errors (for example: invalid inputs, duplicate Blob Units, or exceeding element limits).

## Tasks
1. [ ] Create Storage Structure
Define a Solidity mapping for Blob Unit storage
```sol
mapping(bytes32 => bool) public blobHashes;
```
2. [ ] Add Blob Units Functionality
Accept 3 Composite Unit hashes.
Then validate:
- Composite Unit hashes exist in `compositeHashes`.
- Compute the hash of the Blob Unit:
```sol
bytes32 blobHash = keccak256(abi.encode(hash1, hash2, hash3)); // use encodePacked here?
```
- Check if the Blob Unit already exists in `blobHashes` (**NOTE**: if the blob unit exists the prior step will be needlessly expensive. is there a way to determine if the blob exists before hashing?)
- If it does not exist, store it in the `blobHashes` mapping
3. [ ] Check if Blob Unit is Present Functionality
- Accept a Blob Unit hash as input and return whether it exists in `blobHashes`.
4. [ ] Write Test Cases:
Validate:
- Correct storage of valid Blob Units as 3 Composite Units
- Prevention of duplicate Blob Unit storage
- Rejection of invalid inputs
- Checking the existence of Blob Units
## Deliverables
- [ ] Solidity code to handle Blob Unit creation and deduplication
- [ ] Unit tests with edge cases (e.g., invalid inputs, duplicate combinations)
## Dependencies
- #12 
- #13 
## Example Input and Expected Behavior
1. Input: `hashA`, `hashB`, `hashC`
**Precondition**
- `compositeHashes[hashA] == true`
- `compositeHashes[hashB] == true`
- `compositeHashes[hashC] == true`
**Validation**
- 3 Composite Units are included
- Compute `keccak256(abi.encode(hashA, hashB, hashC))` (Note: use whichever encoding was used above `encode`/`encodePacked`)
- Add the hash to `blobHashes`
- Verify hash of blob is stored in `blobHashes`
2. Input: `hashA`, `hashB`, `hashC` again
3. Invalid Input: `hashA`, `hashC`, `hashD` (2 Composite Units, 1 Atomic Unit)
**Validation**: Reject with error ("Invalid input: must include exactly 3 Composite Units").
4. Invalid Input: `hashA`, `hashC` (2 Composite Units)
**Validation**: Reject with error ("Invalid input: must include exactly 3 Composite Units").
5. Invalid Input: `hashA`, `hashB`, `hashC`, `hashE` (4 Composite Units)
**Validation**: Reject with error ("Invalid input: must include exactly 3 Composite Units").
